# Generated by Django 4.1.7 on 2023-03-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hours', models.DurationField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=25, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('passed_courses', models.ManyToManyField(to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=25, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateTimeField()),
                ('qualification', models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=10)),
                ('add_info', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_study', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=60)),
                ('time_of_study', models.TimeField()),
                ('course', models.ManyToManyField(to='courses.course')),
                ('listener', models.ManyToManyField(to='courses.listener')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_time', models.TimeField()),
                ('days_of_study', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=60)),
                ('course', models.ManyToManyField(to='courses.course')),
                ('listener', models.ManyToManyField(to='courses.listener')),
                ('mentor', models.ManyToManyField(to='courses.mentor')),
            ],
        ),
    ]
